version: '3.9'
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: react-app  
    container_name: react-ctr
    volumes:
      - ./reactApp:/usr/src/app # ローカルをコンテナ内にマウント
    command: sh -c "cd todo-App && npm start"
    # （左:自分のPCポート、右:dookerコンテナのポート）
    ports:
      - "3000:3000"
    # コンテナが勝手に終了しないための設定
    tty: true
    # 標準入出力とエラー出力をコンテナに結びつける設定
    stdin_open: true
    # ホットリロードを行う設定
    environment:
      - CHOKIDAR_USEPOLLING=true