version: '3.9'
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: react-app  
    container_name: react-ctr
    volumes:
      # dockerコンテナ本体の、/usr/src/appを作業場に。
      # ./reactAppでCRAをすると、./reactApp直下に<app名>が作成。
      # なので、./reactApp直下が/usr/src/app直下にコピー。
      # つまり、/usr/src/app/<reactで作成したapp名>となる
      - ./reactApp:/usr/src/app
    command: sh -c "cd todo-App && npm start"
    # （左:自分のPCポート、右:dookerコンテナのポート）
    ports:
      - "3000:3000"
    # コンテナが勝手に終了しないための設定
    tty: true
    # 標準入出力とエラー出力をコンテナに結びつける設定
    stdin_open: true
    # ホットリロードを行う設定
    # environment:
    #   - CHOKIDAR_USEPOLLING=true